apiVersion: apps/v1
kind: Job
metadata:
  name: client
spec:
  replicas: 1
  strategy: {}
  template:
    spec:
      priorityClassName: high-priority
      containers:
        - command:
            - TravelReservation/TravelReservation -t client -w "workloads/"
          image: tianyuli96/faster:latest
          name: client
          ports:
            - containerPort: 15721
          resources:
            requests:
              cpu: 2000m
            limits:
              cpu: 4000m
          envFrom:
            - configMapRef:
                name: env-config
      restartPolicy: Never
