apiVersion: v1
kind: Service
metadata:
  labels:
    service: dprfinder
  name: dprfinder
spec:
  ports:
    - name: "15721"
      port: 15721
      targetPort: 15721
  selector:
    service: dprfinder
