apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: premium-lrs
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Premium_LRS
reclaimPolicy: Delete
volumeBindingMode: Immediate