apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: pubsub1
  name: pubsub1
spec:
  replicas: 1
  selector:
    matchLabels:
      service: pubsub1
  strategy: {}
  template:
    metadata:
      labels:
        service: pubsub1
    spec:
      priorityClassName: high-priority
      containers:
        - command:
            - "EventProcessing/EventProcessing -t worker -n 0"
          image: tianyuli96/faster:latest
          name: pubsub1
          ports:
            - containerPort: 15721
          resources:
            requests:
              cpu: 2000m
            limits:
              cpu: 4000m
      restartPolicy: Always