{{- range .Values.clients }}
apiVersion: batch/v1
kind: Job
metadata:
  name: client{{ .num }}
spec:
  template:
    spec:
      priorityClassName: high-priority
      containers:
        - command:
            - "TravelReservation/TravelReservation"
          args:
            - "-t client"
            - "-w workloads/{{ $.Values.workload }}-client-{{ .num }}"
            - "-n {{ .num }}"
          image: tianyuli96/faster:latest
          name: "service{{ .num }}"
          ports:
            - containerPort: 15721
          resources:
            requests:
              cpu: 2000m
            limits:
              cpu: 4000m
          envFrom:
            - configMapRef:
                name: env-config
      restartPolicy: Never
---
{{- end }}