apiVersion: v1
kind: Service
metadata:
  labels:
    service: "orchestrator"
  name: "orchestrator" 
spec:
  ports:
    - name: "15721"
      port: 15721
      targetPort: {{ .Values.orchestrator_port }}
  selector:
    service: "orchestrator"
