{{- range .Values.workers }}
apiVersion: batch/v1
kind: Job
metadata:
  name: client{{ .num }}
spec:
  template:
    spec:
      priorityClassName: high-priority
      serviceAccountName: deployment-watcher
      initContainers:
        - name: wait-all
          image: bitnami/kubectl
          command: [ "sh", "-c" ]
          args:
            - >
              while true; do
                # Check if all deployments have at least one ready replica
                notReadyCount=$(kubectl get deployments -n dse | grep -c "0/1")
                if [ "$notReadyCount" -eq 0 ]; then
                  echo "All deployments are ready.";
                  break;
                else
                  echo "Waiting for all deployments to be ready. $notReadyCount deployments are not ready.";
                  sleep 1;
                fi;
              done;
      containers:
        - command:
            - "CoordinatorMicrobench/CoordinatorMicrobench"
          args:
            - "-t"
            - "worker"
            - "-i"
            - "{{ .num }}"
            - "-n"
            - "{{ $.Values.num_workers }}"
            - "-d"
            - "{{ $.Values.dep_prob}}"
          image: tianyuli96/faster:latest
          name: "client{{ .num }}"
          ports:
            - containerPort: 15721
          envFrom:
            - configMapRef:
                name: env-config
      restartPolicy: Never
---
{{- end }}