apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: orchestrator
  name: orchestrator
spec:
  replicas: {{ .Values.numOrchestrators }}
  selector:
    matchLabels:
      service: orchestrator
  strategy: {}
  template:
    metadata:
      labels:
        service: orchestrator
    spec:
      priorityClassName: high-priority
      containers:
        - command:
            - # TODO: Fill in
          image: tianyuli96/hotelreservation:latest
          name: orchestrator
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 2000m
            limits:
              cpu: 4000m
      restartPolicy: Always
